-- MIGRATION 01: Core Structure & Data Types
-- Ejecutar en Supabase SQL Editor

-- 1. Estandarización de Tipos de Datos (Precisión Monetaria)
-- Cambiamos FLOAT a NUMERIC(12,2) para evitar errores de redondeo en dinero y stock.

ALTER TABLE sales_prices 
    ALTER COLUMN precio_venta_final TYPE numeric(12,2),
    ALTER COLUMN stock_disponible TYPE numeric(12,2);

ALTER TABLE sales_orders 
    ALTER COLUMN total_amount TYPE numeric(12,2),
    ALTER COLUMN amount_paid TYPE numeric(12,2),
    ALTER COLUMN balance_due TYPE numeric(12,2);

-- Costos de ingredientes requieren más precisión (4 decimales)
ALTER TABLE ingredients 
    ALTER COLUMN costo_base_usd_unidad_minima TYPE numeric(12,4);

ALTER TABLE production_logs 
    ALTER COLUMN costo_total_tanda TYPE numeric(12,2);

-- 2. Restricción de Integridad (Blindaje de Stock)
-- Esto impedirá que el stock baje de cero a nivel de base de datos.
ALTER TABLE sales_prices 
    ADD CONSTRAINT check_stock_no_negativo CHECK (stock_disponible >= 0);

-- 3. Tabla Kardex (Historial de Movimientos)
-- Registra cada cambio en el inventario para auditoría total.
CREATE TABLE IF NOT EXISTS inventory_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- O uuid si prefieres
    product_id bigint REFERENCES sales_prices(id) ON DELETE RESTRICT,
    transaction_type varchar(50) NOT NULL, -- 'VENTA', 'PRODUCCION', 'MERMA', 'AJUSTE'
    quantity numeric(12,2) NOT NULL,
    old_stock numeric(12,2), -- Snapshot del stock antes del movimiento (opcional, útil debug)
    new_stock numeric(12,2), -- Snapshot del stock después
    reference_id bigint, -- ID de la venta o log de producción
    reason text,
    created_at timestamptz DEFAULT now()
);

-- 4. Corrección de Integridad Referencial
-- Aseguramos que las tablas históricas apunten a ids reales.

-- Añadimos columna product_id a ventas si no existe
ALTER TABLE sales_orders 
    ADD COLUMN IF NOT EXISTS product_id bigint REFERENCES sales_prices(id);

-- Añadimos columna recipe_id a logs de producción
ALTER TABLE production_logs 
    ADD COLUMN IF NOT EXISTS recipe_id bigint REFERENCES recipes(id);

-- NOTA: Si tus tablas usan UUID como id en lugar de bigint, 
-- cambia 'bigint' por 'uuid' en las definiciones anteriores.
