-- MIGRATION 09: Catalog Composition & Real-Time Costs
-- Ensures the product assembly structure and cost calculation views are robust.

-- 1. Create the Main Table
CREATE TABLE IF NOT EXISTS public.catalog_composition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_id BIGINT NOT NULL REFERENCES public.sales_prices(id) ON DELETE CASCADE,
    recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE SET NULL,
    supply_id BIGINT REFERENCES public.supplies(id) ON DELETE SET NULL,
    quantity NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Constraint: Either recipe or supply, but not both
    CONSTRAINT recipe_or_supply_check CHECK (
        (recipe_id IS NOT NULL AND supply_id IS NULL) OR
        (recipe_id IS NULL AND supply_id IS NOT NULL)
    )
);

-- 2. Create the Detailed Costs View (Real-Time)
CREATE OR REPLACE VIEW public.v_catalog_costs AS
WITH component_costs AS (
    SELECT 
        cc.catalog_id,
        cc.quantity,
        CASE 
            WHEN cc.recipe_id IS NOT NULL THEN (SELECT total_estimated_cost_1kg_base / 1000 FROM v_production_costs vpc WHERE vpc.recipe_id = cc.recipe_id)
            WHEN cc.supply_id IS NOT NULL THEN (SELECT last_purchase_price / equivalence FROM supplies s WHERE s.id = cc.supply_id)
            ELSE 0 
        END as cost_per_unit
    FROM catalog_composition cc
)
SELECT 
    sp.id as catalog_id,
    sp.product_name,
    sp.precio_venta_final,
    COALESCE(SUM(c.quantity * c.cost_per_unit), 0) as total_production_cost,
    sp.precio_venta_final - COALESCE(SUM(c.quantity * c.cost_per_unit), 0) as margin_usd,
    CASE 
        WHEN sp.precio_venta_final > 0 THEN 
            ((sp.precio_venta_final - COALESCE(SUM(c.quantity * c.cost_per_unit), 0)) / sp.precio_venta_final) * 100 
        ELSE 0 
    END as margin_percentage
FROM sales_prices sp
LEFT JOIN component_costs c ON sp.id = c.catalog_id
GROUP BY sp.id, sp.product_name, sp.precio_venta_final;

-- 3. RLS Policies
ALTER TABLE public.catalog_composition ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow All" ON public.catalog_composition FOR ALL USING (true);

-- 4. Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
